#!/usr/bin/env bash
n=1
while [ $n -lt 21 ]
do
	echo "$n"
	case "$n" in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	((n++))
done
