#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes
n=0
i=1
while [ $n -lt 13 ]
do
	echo "Hour: $n"
	while ((i <= 59))
	do
		echo "$i"
		((i++))
	done
	((i = 1))
	((n++))
done
